name: Deploy

on:
  workflow_run:
    workflows: ["PHP CI"]
    types:
      - completed
  push:
    branches: [ "main" ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:

    runs-on: ubuntu-latest

    needs:
      - ci

    steps:

      - uses: actions/checkout@v3

      # -----------
      # --- NPM ---
      # -----------
      - name: Install npm dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run production

      - name: Install Composer Dependecies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      # ----------------------------
      # --- Copy new project dir ---
      # ----------------------------
      - name: Copy new project dir
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          rm: true
          source: "."
          target: "/var/www/readingprogress"


      # --------------------------
      # --- Update project dir ---
      # --------------------------
      - name: Update project
        uses: appleboy/ssh-action@master
        env:
          PROJECT_DIR: "/var/www/readingprogress"
          STORAGE_APP_DIR: "/root/readingprogress/storage/app"
          ENV_FILE: "/root/readingprogress/.env"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: PROJECT_DIR, ENV_FILE, STORAGE_APP_DIR
          script_stop: true
          script: |
            cd $PROJECT_DIR
            cp $ENV_FILE .env
            rm -rf storage/app
            ln -sf $STORAGE_APP_DIR $PROJECT_DIR/storage/app
            chown -R www-data:www-data $PROJECT_DIR
            chmod -R ug+rwx storage bootstrap/cache
            php artisan storage:link
            php artisan clear-compiled
            php artisan optimize
            php artisan migrate --force
